requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    submodule: true
configuration:
  template_dir:
  - "pypi-mobans:templates"
  - ".moban.d"
  configuration: gease.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/requirements.txt.jj2"
  - test.sh: test.script.jj2
  - 'gease/_version.py': 'version.py.jj2'
